
import jsPDF from 'jspdf';

interface ReportMetadata {
    groupName: string;
    date: string;
    generatedBy: string;
}

/**
 * Generates an "Audit Grade" PDF.
 * It parses the Markdown-like text from the engineering engine and renders it
 * as a formal document with headers, footers, and proper typography.
 */
export const generateAuditGradePdf = (reportContent: string, metadata: ReportMetadata) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'pt',
        format: 'letter'
    });

    const margin = 50;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const usableWidth = pageWidth - (margin * 2);
    let y = margin;

    // --- Helper Functions ---

    const checkPageBreak = (heightToAdd: number) => {
        if (y + heightToAdd > pageHeight - margin) {
            drawFooter();
            doc.addPage();
            y = margin + 20; // Start a bit lower on subsequent pages
        }
    };

    const drawFooter = () => {
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.setFont('helvetica', 'italic');
        doc.text(`Page ${pageCount} | Generated by PLCortex Engineering Assistant`, margin, pageHeight - 20);
        doc.text(metadata.date, pageWidth - margin, pageHeight - 20, { align: 'right' });
    };

    // --- Header Section ---
    
    // Company / App Logo Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(63, 81, 181); // Indigo
    doc.text("PLCortex", margin, y);
    
    // Document Title
    doc.setFontSize(14);
    doc.setTextColor(0); // Black
    doc.text("OFFICIAL SHIFT HANDOVER REPORT", pageWidth - margin, y, { align: 'right' });
    
    y += 25;
    
    // Metadata Box
    doc.setDrawColor(200);
    doc.setFillColor(245, 247, 250);
    doc.rect(margin, y, usableWidth, 50, 'F');
    doc.rect(margin, y, usableWidth, 50, 'S');
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    const metaY = y + 20;
    doc.text("GROUP / AREA:", margin + 15, metaY);
    doc.text("DATE GENERATED:", margin + 200, metaY);
    doc.text("AUTHORIZED BY:", margin + 380, metaY);
    
    doc.setFont('helvetica', 'normal');
    const valY = metaY + 15;
    doc.text(metadata.groupName.toUpperCase(), margin + 15, valY);
    doc.text(metadata.date, margin + 200, valY);
    doc.text(metadata.generatedBy || "System Admin", margin + 380, valY);

    y += 70; // Move below metadata box

    // --- Body Content Parser ---
    
    const lines = reportContent.split('\n');
    
    doc.setFontSize(11);
    doc.setTextColor(20);

    lines.forEach((line) => {
        const cleanLine = line.trim();
        if (!cleanLine) {
            y += 10; // Paragraph spacing
            return;
        }

        // Detect Headers (Markdown style # or just uppercase heavy lines)
        if (cleanLine.startsWith('#') || cleanLine.startsWith('**') && cleanLine.endsWith('**')) {
            const headerText = cleanLine.replace(/[#*]/g, '').trim();
            checkPageBreak(30);
            
            y += 15;
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(13);
            doc.setTextColor(63, 81, 181); // Indigo header
            doc.text(headerText.toUpperCase(), margin, y);
            
            // Underline header
            y += 5;
            doc.setDrawColor(63, 81, 181);
            doc.setLineWidth(1);
            doc.line(margin, y, margin + 200, y); // Partial underline
            
            y += 15;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            doc.setTextColor(20); // Reset to black
            return;
        }

        // Detect List Items
        let indent = 0;
        let textToPrint = cleanLine;
        let prefix = "";

        if (cleanLine.startsWith('- ') || cleanLine.startsWith('* ')) {
            indent = 15;
            prefix = "• ";
            textToPrint = cleanLine.substring(2);
        } else if (/^\d+\./.test(cleanLine)) {
            indent = 15;
            prefix = cleanLine.split(' ')[0] + " "; // Keep "1. "
            textToPrint = cleanLine.replace(/^\d+\.\s*/, '');
        }

        // Detect Bold keys inside lines (Simple parser: "Key: Value")
        const parts = textToPrint.split('**:');
        let isBoldKey = false;
        if (parts.length > 1 || textToPrint.includes('**')) {
             // Basic formatting cleanup for the PDF
             textToPrint = textToPrint.replace(/\*\*/g, '');
             // If it looks like "Label: Value", bold the label
             isBoldKey = textToPrint.includes(':'); 
        }

        if (isBoldKey) {
            doc.setFont('helvetica', 'bold');
        } else {
            doc.setFont('helvetica', 'normal');
        }

        // Text Wrapping
        const maxLineWidth = usableWidth - indent;
        const wrappedLines = doc.splitTextToSize(prefix + textToPrint, maxLineWidth);
        
        checkPageBreak(wrappedLines.length * 14);

        doc.text(wrappedLines, margin + indent, y);
        y += (wrappedLines.length * 14);
    });

    // --- End of Report Signature Line ---
    checkPageBreak(100);
    y += 40;
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + 200, y);
    doc.setFontSize(10);
    doc.text("Supervisor Signature", margin, y + 15);

    drawFooter(); // Draw footer on last page
    
    // Save
    const safeDate = metadata.date.replace(/[\/:\s]/g, '_');
    doc.save(`ShiftReport_${metadata.groupName}_${safeDate}.pdf`);
};
